/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/youtube": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Ingest Youtube
         * @description Download YouTube audio into the library.
         *
         *     Same video URL → same file_id (`yt_{video_id}`) → returns cached entry, no
         *     redownload. Personal-practice use; copyright is the caller's responsibility.
         */
        post: operations["api_ingest_youtube_api_v1_ingest_youtube_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Library List */
        get: operations["api_library_list_api_v1_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Library Get */
        get: operations["api_library_get_api_v1_library__file_id__get"];
        put?: never;
        post?: never;
        /** Api Library Delete */
        delete: operations["api_library_delete_api_v1_library__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/{file_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Library Audio */
        get: operations["api_library_audio_api_v1_library__file_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/{file_id}/file/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Library File
         * @description Serve any artifact inside the track dir (stems/vocals.wav, midi/vocal.mid, ...).
         */
        get: operations["api_library_file_api_v1_library__file_id__file__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze/beats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Analyze Beats
         * @description Beat / onset / energy peak extraction (Herta CPU, librosa).
         */
        post: operations["api_analyze_beats_api_v1_analyze_beats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze/chords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Analyze Chords
         * @description Chord recognition via Nous GPU worker (Crema). 503 if worker unreachable.
         */
        post: operations["api_analyze_chords_api_v1_analyze_chords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/separate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Separate
         * @description Source separation via Nous GPU worker (Demucs). Stems are mirrored to library.
         */
        post: operations["api_separate_api_v1_separate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze/pitch-to-midi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Pitch To Midi
         * @description Pitch -> MIDI transcription via Nous GPU worker (Basic Pitch). Mirrored to library.
         */
        post: operations["api_pitch_to_midi_api_v1_analyze_pitch_to_midi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BeatAnalysis */
        BeatAnalysis: {
            /**
             * File Id
             * @description Library file_id if persisted
             */
            file_id?: string | null;
            /** Duration Sec */
            duration_sec: number;
            /** Tempo */
            tempo: number;
            /** Beats */
            beats: number[];
            /** Onsets */
            onsets: number[];
            /** Energy Peaks */
            energy_peaks: components["schemas"]["EnergyPeak"][];
        };
        /** Body_api_analyze_beats_api_v1_analyze_beats_post */
        Body_api_analyze_beats_api_v1_analyze_beats_post: {
            /** Audio */
            audio?: string;
            /** File Id */
            file_id?: string;
            /**
             * Hop Length
             * @default 512
             */
            hop_length: number;
        };
        /** Body_api_analyze_chords_api_v1_analyze_chords_post */
        Body_api_analyze_chords_api_v1_analyze_chords_post: {
            /** Audio */
            audio?: string;
            /** File Id */
            file_id?: string;
            /**
             * Pre Separate
             * @default false
             */
            pre_separate: boolean;
        };
        /** Body_api_ingest_youtube_api_v1_ingest_youtube_post */
        Body_api_ingest_youtube_api_v1_ingest_youtube_post: {
            /** Url */
            url: string;
        };
        /** Body_api_pitch_to_midi_api_v1_analyze_pitch_to_midi_post */
        Body_api_pitch_to_midi_api_v1_analyze_pitch_to_midi_post: {
            /** Audio */
            audio?: string;
            /** File Id */
            file_id?: string;
            /**
             * Instrument Hint
             * @default auto
             */
            instrument_hint: string;
            /**
             * Pre Separate
             * @default false
             */
            pre_separate: boolean;
        };
        /** Body_api_separate_api_v1_separate_post */
        Body_api_separate_api_v1_separate_post: {
            /** Audio */
            audio?: string;
            /** File Id */
            file_id?: string;
            /**
             * Model
             * @default htdemucs
             */
            model: string;
        };
        /** ChordAnalysis */
        ChordAnalysis: {
            /** File Id */
            file_id?: string | null;
            /** Elapsed Sec */
            elapsed_sec: number;
            /** Duration Sec */
            duration_sec: number;
            /** Model */
            model: string;
            /** Pre Separated */
            pre_separated: boolean;
            /** Tempo Hint */
            tempo_hint?: number | null;
            /** Chords */
            chords: components["schemas"]["ChordSegment"][];
        };
        /** ChordSegment */
        ChordSegment: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Label
             * @description Harte chord notation, e.g. 'C:maj', 'A:min7', 'N' for no-chord
             */
            label: string;
            /** Confidence */
            confidence: number;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** File Id */
            file_id: string;
            /** Deleted */
            deleted: boolean;
        };
        /** EnergyPeak */
        EnergyPeak: {
            /** Time */
            time: number;
            /** Strength */
            strength: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestResponse */
        IngestResponse: {
            /** File Id */
            file_id: string;
            /** Title */
            title: string;
            /** Duration Sec */
            duration_sec: number;
            /** Source Url */
            source_url: string;
            /**
             * Cached
             * @description True if existing library entry was returned (no download)
             */
            cached: boolean;
        };
        /** LibraryEntry */
        LibraryEntry: {
            /** File Id */
            file_id: string;
            /** Title */
            title: string;
            /** Source Url */
            source_url?: string | null;
            /** Duration Sec */
            duration_sec: number;
            /** Created At */
            created_at: string;
            /**
             * Analyses
             * @description e.g. ['beats','chords','stems','pitch-to-midi:vocal']
             */
            analyses?: string[];
        };
        /** LibraryList */
        LibraryList: {
            /** Count */
            count: number;
            /** Entries */
            entries: components["schemas"]["LibraryEntry"][];
        };
        /** PitchMidi */
        PitchMidi: {
            /** File Id */
            file_id?: string | null;
            /** Elapsed Sec */
            elapsed_sec: number;
            /** Duration Sec */
            duration_sec: number;
            /** Instrument Hint */
            instrument_hint: string;
            /** Pre Separated */
            pre_separated: boolean;
            /** Note Count */
            note_count: number;
            /** Midi Url */
            midi_url: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /** SeparationResult */
        SeparationResult: {
            /** File Id */
            file_id?: string | null;
            /** Elapsed Sec */
            elapsed_sec: number;
            /** Model */
            model: string;
            /** Duration Sec */
            duration_sec?: number | null;
            /**
             * Stems
             * @description stem_name -> URL (library or worker)
             */
            stems: {
                [key: string]: string;
            };
            /**
             * Expires At
             * @description Worker TTL; absent if persisted to library
             */
            expires_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_ingest_youtube_api_v1_ingest_youtube_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_api_ingest_youtube_api_v1_ingest_youtube_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_library_list_api_v1_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryList"];
                };
            };
        };
    };
    api_library_get_api_v1_library__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_library_delete_api_v1_library__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_library_audio_api_v1_library__file_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_library_file_api_v1_library__file_id__file__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_analyze_beats_api_v1_analyze_beats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_api_analyze_beats_api_v1_analyze_beats_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeatAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_analyze_chords_api_v1_analyze_chords_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_api_analyze_chords_api_v1_analyze_chords_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChordAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_separate_api_v1_separate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_api_separate_api_v1_separate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeparationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_pitch_to_midi_api_v1_analyze_pitch_to_midi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_api_pitch_to_midi_api_v1_analyze_pitch_to_midi_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PitchMidi"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
